### ISSUE TITLE
Setup du projet

### ISSUE THREAD

**Issue by charlesen** [bigben35/OCR_5_Blog#62]
### Git clone

Depuis votre terminal, lancez la commande suivante dans le dossier où souhaitez stocker votre projet

- `git clone git@github.com:bigben35/OCR_5_Blog.git`

### Installation de package (`phpdotenv` + `whoops`) + activation de l'autoloading

accédez au dossier `OCR_5_Blog` et lancez la commande

- `composer install` 

Si besoin d'installer composer, suivre les étapes suivantes
<details>

-   **Windows** : il suffit de [télécharger l'exécutable proposé sur le site](https://getcomposer.org/Composer-Setup.exe) et vous laissez guider. Voici une [documentation qui vous explique comment faire](https://www.hostinger.fr/tutoriels/comment-installer-et-utiliser-composer), pas à pas.

- **Linux** : dans un terminal, lancez les commandes suivantes :

```bash
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```

</details>

### Variables d'environnement + Base de données

> PHP Warning:  Unknown: Failed to open stream: Invalid argument in Unknown on line 0
[Tue Oct  4 21:20:14 2022] PHP Fatal error:  Failed opening required '.' (include_path='.:/usr/share/php') in Unknown on line 

Afin de ne pas avoir ce bug, on va créer le fichier .env à la racine du projet en copiant-collant le le fichie `.env.example`.

On édite ensuite le fichier `.env` avec les valeurs de connexion à la base de donnnées

```bash
DB_HOST=localhost
DB_PORT=3306
DB_USERNAME=username
DB_PASSWORD=password
DB_NAME=blob_ocr

APP_ENV=development

```

Il faut ensuite d'importer le fichier [`blog-ocr-version-finale.sql`](https://github.com/bigben35/OCR_5_Blog/blob/main/blog-ocr-version-finale.sql) présent à la racine du projet

### Démarrage du projet 

Depuis un terminal, vous pouvez lancer la commande suivante :  
- `php -S localhost:8080 -t .`

Qui va démarrer votre projet grâce au serveur intégré de PHP.

Mais vous pouvez aussi utiliser WampServer et configurer un virtualhost pointant sur le dossier du projet.

Accès à la page d'administration

Pour vous connecter en tant qu'Admin, utilisez les identifiants de connexion suivants
- Email : jojo@gmail.com
- password : azerty 

Si vous souhaitez utiliser un autre utilisateur (celui que vous avez créé par exemple), vous pouvez modifier le role (par 1) dans la base de données.

Félicitations : votre projet est lancé 🎉

**Comment by bigben35** [comment]
Je te remercie !
Je vais apporter les modifs que tu m'as transmis.

A demain,
Cordialement,

Josselin

Le mar. 4 oct. 2022 à 21:24, Charles EDOU NZE ***@***.***> a
écrit :
